repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
        entry: isort
        stages: [commit, merge-commit, push, manual]
        require_serial: true
        language: python
        types_or: [cython, pyi, python]
        args: ["--filter-files"]
        minimum_pre_commit_version: "2.9.2"

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8
        description: "Start enforcing style consistency across Python project."
        entry: flake8
        language: python
        types: [python]
        require_serial: true

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
      - id: autopep8
        name: autopep8
        description: A tool that automatically formats Python code to conform to the PEP 8 style guide.
        entry: autopep8
        language: python
        types: [python]
        args: [-i]
